CREATE DATABASE IF NOT EXISTS master_db;

USE master_db;

CREATE TABLE USERS(
    IDENTIFICATION_NUMBER VARCHAR(13) NOT NULL,
    FIRST_NAME VARCHAR(100) DEFAULT NULL,
    SECOND_NAME VARCHAR(100) DEFAULT NULL,
    LAST_NAME VARCHAR(100) DEFAULT NULL,
    SECOND_LASTNAME VARCHAR(100) DEFAULT NULL,
    DATE_BIRTH DATE DEFAULT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    PHONE VARCHAR(20) DEFAULT NULL,
    CELLPHONE VARCHAR(20) DEFAULT NULL,
    GENDER VARCHAR(1) DEFAULT NULL,
    USERNAME VARCHAR(100) DEFAULT NULL,
    PASSWORD VARCHAR(100) DEFAULT NULL,
    PHOTO BLOB DEFAULT NULL,
    PRIMARY KEY (IDENTIFICATION_NUMBER)
);

CREATE TABLE MEDICATIONS (
    MEDICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) DEFAULT NULL,
    PHOTO BLOB DEFAULT NULL,
    AMOUNT VARCHAR(255) DEFAULT NULL
);

CREATE TABLE DOCTORS (
    IDENTIFICATION_NUMBER VARCHAR(13) PRIMARY KEY,
    NAME VARCHAR(255) DEFAULT NULL,
    PHOTO BLOB DEFAULT NULL
);

CREATE TABLE CONSULTATIONS (
    CONSULTATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEDICATION_ID INT,
    IDENTIFICATION_NUMBER_USER VARCHAR(13),
    IDENTIFICATION_NUMBER_DOCTOR VARCHAR(13),
    SCHEDULE date DEFAULT NULL,
    OBSERVATION VARCHAR(255) DEFAULT NULL,
    SYMBOL VARCHAR(10) DEFAULT NULL,
    FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATIONS(MEDICATION_ID),
    FOREIGN KEY (IDENTIFICATION_NUMBER_USER) REFERENCES USERS(IDENTIFICATION_NUMBER),
    FOREIGN KEY (IDENTIFICATION_NUMBER_DOCTOR) REFERENCES DOCTORS(IDENTIFICATION_NUMBER)
);

-- Insert 1
INSERT INTO USERS (IDENTIFICATION_NUMBER, FIRST_NAME, LAST_NAME, DATE_BIRTH, EMAIL, GENDER, USERNAME, PASSWORD)
VALUES ('1234567890123', 'John', 'Doe', '1990-01-15', 'john@example.com', 'M', 'johndoe', 'password123');

-- Insert 2
INSERT INTO USERS (IDENTIFICATION_NUMBER, FIRST_NAME, LAST_NAME, DATE_BIRTH, EMAIL, GENDER, USERNAME, PASSWORD)
VALUES ('9876543210987', 'Jane', 'Smith', '1995-05-20', 'jane@example.com', 'F', 'janesmith', 'pass987');

-- Insert 3
INSERT INTO USERS (IDENTIFICATION_NUMBER, FIRST_NAME, LAST_NAME, DATE_BIRTH, EMAIL, GENDER, USERNAME, PASSWORD)
VALUES ('4567890123456', 'Michael', 'Johnson', '1988-11-03', 'michael@example.com', 'M', 'michaelj', 'mikepass');


-- Insert para AZITROMICINA
INSERT INTO MEDICATIONS (NAME, AMOUNT)
VALUES ('AZITROMICINA', '500 mg');


-- Insert para IBUPROFENO
INSERT INTO MEDICATIONS (NAME, AMOUNT)
VALUES ('IBUPROFENO', '400 mg');


-- Insert para PARACETAMOL
INSERT INTO MEDICATIONS (NAME, AMOUNT)
VALUES ('PARACETAMOL', '500 mg');


-- Insert para KATHERINE LOZANO
INSERT INTO DOCTORS (IDENTIFICATION_NUMBER, NAME)
VALUES ('1234567890123', 'KATHERINE LOZANO');

-- Insert para EDWIN AVILA
INSERT INTO DOCTORS (IDENTIFICATION_NUMBER, NAME)
VALUES ('9876543210987', 'EDWIN AVILA');




